In [135]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [136]:
df = sns.load_dataset('penguins')

In [137]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [138]:
df.shape

(344, 7)

In [139]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [140]:
from sklearn.impute import SimpleImputer

numerical_columns = ['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']
categrocal_columns = ['sex']

num_impute = SimpleImputer(strategy='median')
df[numerical_columns] = num_impute.fit_transform(df[numerical_columns])

cat_impute = SimpleImputer(strategy='most_frequent')
df[categrocal_columns] = cat_impute.fit_transform(df[categrocal_columns])

In [141]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [142]:
X = df.iloc[:,1:]
y = df.iloc[:,0:1]

In [143]:
y

species
0    Adelie
1    Adelie
2    Adelie
3    Adelie
4    Adelie
..      ...
339  Gentoo
340  Gentoo
341  Gentoo
342  Gentoo
343  Gentoo

[344 rows x 1 columns]

In [144]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler

y_encode = LabelEncoder()
y= y_encode.fit_transform(y)

/home/suhas/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [145]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [146]:
class_labels = y_encode.classes_

print(class_labels)

['Adelie' 'Chinstrap' 'Gentoo']


In [147]:
for i,label in enumerate(class_labels):
    print(f"{i}:{label}")

0:Adelie
1:Chinstrap
2:Gentoo


In [148]:
from sklearn.model_selection import train_test_split,cross_val_score

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [149]:
X_train.head()

island  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
66      Biscoe            35.5           16.2              195.0       3350.0   
229     Biscoe            46.8           15.4              215.0       5150.0   
7    Torgersen            39.2           19.6              195.0       4675.0   
140      Dream            40.2           17.1              193.0       3400.0   
323     Biscoe            49.1           15.0              228.0       5500.0   

        sex  
66   Female  
229    Male  
7      Male  
140  Female  
323    Male

In [150]:
from sklearn.compose import ColumnTransformer

# Define Preprocessing steps
ohe_encode = OneHotEncoder(drop='first',sparse=False)

# Define transformation for categorical and numerical columns
column_tranformation = ColumnTransformer(
    transformers= [
        ('island',ohe_encode,['island']),
        ('sex',ohe_encode,['sex'])
    ],remainder='passthrough'
)

In [151]:
# Preprocess piepline (imputation,ohe-hot encoding,scaling)
from sklearn.pipeline import Pipeline



pipeline_preprocessor = Pipeline(
    steps= [
        ('column_tranformation',column_tranformation),
        ('scaler',StandardScaler())
    ]
)

In [152]:
# Define algorithms for categorical and numerical columns
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import joblib
from sklearn.linear_model import LogisticRegression


algorithms_test = {
    "random_forest": RandomForestClassifier(),
    "decision_tree": DecisionTreeClassifier(),
    "xgboost": xgb.XGBClassifier(use_label_encoder=False,eval_metric='mlogloss'),
    "svm": SVC(class_weight='balanced'),
    "logistic_regression": LogisticRegression()

}

results= {}
piepline_info = {}

#Train and evaluate the each algorithm
for name,algo in algorithms_test.items():
    #Create a pipeline to apply preprocessor(column transform) for each algorithm
    fit_pipepline = Pipeline(
        steps= [
            ('preprocess_columns',pipeline_preprocessor),
            ("alogrithms",algo)
        ]
    )

    # Train the each algorthim
    fit_pipepline.fit(X_train,y_train)

    #save the trained algorithms in .pkl file
    joblib.dump(fit_pipepline,f"{name}.pkl")
    piepline_info[name] = fit_pipepline

    # Make the predictions on the test data
    y_pred = fit_pipepline.predict(X_test)

    # calculate and store the results
    accuracy = accuracy_score(y_test,y_pred)
    clf_report = classification_report(y_test,y_pred)
    cf_matrix = confusion_matrix(y_test,y_pred)
    cv = cross_val_score(fit_pipepline,X_train,y_train,scoring='accuracy',cv=5)
    cv_mean = cv.mean()

    results[name] = {
        "accuracy": accuracy,
        "clf_report": clf_report,
        'cf_matrix': cf_matrix,
        'cv': cv,
        'cv_mean': cv_mean
    }

    print(f"{name}")
    print(f"Accuracy for {name}: {accuracy}")
    print(f"Classification Report for {name}: \n{clf_report}")
    print(f"Confusion Matrix for {name}: \n{cf_matrix}")
    print(f"Cross Validation for {name}: {cv}")
    print(f"Cross Validation  Mean for {name}: {cv_mean}")
    print('-'*50)


random_forest
Accuracy for random_forest: 1.0
Classification Report for random_forest: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        21

    accuracy                           1.00        69
   macro avg       1.00      1.00      1.00        69
weighted avg       1.00      1.00      1.00        69

Confusion Matrix for random_forest: 
[[32  0  0]
 [ 0 16  0]
 [ 0  0 21]]
Cross Validation for random_forest: [0.98181818 0.96363636 0.96363636 1.         0.98181818]
Cross Validation  Mean for random_forest: 0.9781818181818182
--------------------------------------------------
decision_tree
Accuracy for decision_tree: 0.9710144927536232
Classification Report for decision_tree: 
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        32
           1       1.00      1.00      1