In [69]:
import numpy as np
import pandas as pd

In [70]:
df = pd.read_csv('/home/suhas/Desktop/office/Data Science/Notes/Data Analysis/Data/titanic.csv',usecols=['age','pclass','fare','survived'])

In [71]:
df.sample(5)

survived  pclass   age     fare
794         0       3  25.0   7.8958
569         1       3  32.0   7.8542
301         1       3   NaN  23.2500
185         0       1   NaN  50.0000
222         0       3  51.0   8.0500

In [72]:
df.isnull().mean()*100

survived     0.00000
pclass       0.00000
age         19.86532
fare         0.00000
dtype: float64

In [73]:
X = df.drop(columns=['survived'])
y = df['survived']

In [74]:
X

pclass   age     fare
0         3  22.0   7.2500
1         1  38.0  71.2833
2         3  26.0   7.9250
3         1  35.0  53.1000
4         3  35.0   8.0500
..      ...   ...      ...
886       2  27.0  13.0000
887       1  19.0  30.0000
888       3   NaN  23.4500
889       1  26.0  30.0000
890       3  32.0   7.7500

[891 rows x 3 columns]

In [75]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [76]:
y_test.head()

707    1
37     0
615    1
169    0
68     1
Name: survived, dtype: int64

In [ ]:
from sklearn.impute import KNNImputer

# knn = KNNImputer()
knn = KNNImputer(n_neighbors=3,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)


In [78]:
X_test_trf

array([[  1.        ,  42.        ,  26.2875    ],
       [  3.        ,  21.        ,   8.05      ],
       [  2.        ,  24.        ,  65.        ],
       [  3.        ,  28.        ,  56.4958    ],
       [  3.        ,  17.        ,   7.925     ],
       [  3.        ,  30.        ,   7.8958    ],
       [  1.        ,  80.        ,  30.        ],
       [  3.        ,  25.        ,   7.25      ],
       [  1.        ,  50.        , 133.65      ],
       [  2.        ,  25.        ,  26.        ],
       [  2.        ,  35.        ,  26.        ],
       [  1.        ,  35.        ,  90.        ],
       [  2.        ,  55.        ,  16.        ],
       [  3.        ,  29.        ,  56.4958    ],
       [  3.        ,  29.        ,  56.4958    ],
       [  3.        ,  19.        ,   7.8542    ],
       [  3.        ,  29.        ,  15.2458    ],
       [  3.        ,  49.        ,   0.        ],
       [  3.        ,  18.        ,  14.4542    ],
       [  3.        ,  65.     

In [79]:
from sklearn.linear_model import LogisticRegression


lr = LogisticRegression()
lr.fit(X_train_trf,y_train)
y_pred = lr.predict(X_test_trf)

In [80]:
X_train_trf

array([[  1.        ,  40.        ,  27.7208    ],
       [  3.        ,   4.        ,  16.7       ],
       [  3.        ,  47.        ,   9.        ],
       ...,
       [  1.        ,  71.        ,  49.5042    ],
       [  1.        ,  32.66666667, 221.7792    ],
       [  1.        ,  49.76289518,  25.925     ]])

In [81]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.7150837988826816

### Comparision with simple imputer

In [82]:
## Comparision with simple imputer - mean
from sklearn.impute import SimpleImputer

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [83]:
X_test_trf2

array([[  1.        ,  42.        ,  26.2875    ],
       [  3.        ,  21.        ,   8.05      ],
       [  2.        ,  24.        ,  65.        ],
       [  3.        ,  28.        ,  56.4958    ],
       [  3.        ,  17.        ,   7.925     ],
       [  3.        ,  30.        ,   7.8958    ],
       [  1.        ,  80.        ,  30.        ],
       [  3.        ,  25.        ,   7.25      ],
       [  1.        ,  50.        , 133.65      ],
       [  2.        ,  25.        ,  26.        ],
       [  2.        ,  35.        ,  26.        ],
       [  1.        ,  35.        ,  90.        ],
       [  2.        ,  55.        ,  16.        ],
       [  3.        ,  29.78590426,  56.4958    ],
       [  3.        ,  29.78590426,  56.4958    ],
       [  3.        ,  19.        ,   7.8542    ],
       [  3.        ,  29.78590426,  15.2458    ],
       [  3.        ,  49.        ,   0.        ],
       [  3.        ,  18.        ,  14.4542    ],
       [  3.        ,  65.     

In [84]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)
y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978