In [68]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import StandardScaler


In [69]:
from sklearn.datasets import load_iris

In [70]:
X,y = load_iris(return_X_y=True)

In [71]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [72]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [73]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [74]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [75]:
X_test_scaled

array([[ 0.35451684, -0.58505976,  0.55777524,  0.02224751],
       [-0.13307079,  1.65083742, -1.16139502, -1.17911778],
       [ 2.30486738, -1.0322392 ,  1.8185001 ,  1.49058286],
       [ 0.23261993, -0.36147005,  0.44316389,  0.4227026 ],
       [ 1.2077952 , -0.58505976,  0.61508092,  0.28921757],
       [-0.49876152,  0.75647855, -1.27600637, -1.04563275],
       [-0.2549677 , -0.36147005, -0.07258719,  0.15573254],
       [ 1.32969211,  0.08570939,  0.78699794,  1.49058286],
       [ 0.47641375, -1.92659808,  0.44316389,  0.4227026 ],
       [-0.01117388, -0.80864948,  0.09932984,  0.02224751],
       [ 0.84210448,  0.30929911,  0.78699794,  1.09012776],
       [-1.23014297, -0.13788033, -1.33331205, -1.44608785],
       [-0.37686461,  0.98006827, -1.39061772, -1.31260282],
       [-1.10824606,  0.08570939, -1.27600637, -1.44608785],
       [-0.86445224,  1.65083742, -1.27600637, -1.17911778],
       [ 0.59831066,  0.53288883,  0.55777524,  0.55618763],
       [ 0.84210448, -0.

In [76]:
lr = LogisticRegression()
lr.fit(X_train_scaled,y_train)
y_pred = lr.predict(X_test_scaled)

print("Accuracy Score:",accuracy_score(y_test,y_pred))
print("Confussion Matrix:",confusion_matrix(y_test,y_pred))

Accuracy Score: 1.0
Confussion Matrix: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [77]:
des = DecisionTreeClassifier()
des.fit(X_train_scaled,y_train)
y_pred1 = des.predict(X_test_scaled)

print("Accuracy score:\n",accuracy_score(y_test,y_pred1))
print("Confussion Matrix:\n",confusion_matrix(y_test,y_pred1))



Accuracy score:
 1.0
Confussion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [78]:
df = pd.read_csv('/home/suhas/Desktop/office/Data Science/Notes/Data Analysis/Data/Iris.csv')

In [79]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [80]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Species'] = encoder.fit_transform(df['Species'])

In [81]:
df.sample(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
84    85            5.4           3.0            4.5           1.5        1
146  147            6.3           2.5            5.0           1.9        2
62    63            6.0           2.2            4.0           1.0        1
82    83            5.8           2.7            3.9           1.2        1
50    51            7.0           3.2            4.7           1.4        1

In [82]:
X = df.iloc[:,1:-1]
y = df.iloc[:,-1]

In [83]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [84]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [85]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [86]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [87]:
y_pred = clf1.predict(X_test)
y_pred1 = clf1.predict(X_test)

In [88]:
print("Accuracy Logistic Regression:",accuracy_score(y_test,y_pred))
print("Accuracy Descision Tree:",accuracy_score(y_test,y_pred1))


Accuracy Logistic Regression: 1.0
Accuracy Descision Tree: 1.0


In [89]:
print("Confussion Matrix LR:\n",confusion_matrix(y_test,y_pred))
print("Confussion Matrix DT:\n",confusion_matrix(y_test,y_pred1))


Confussion Matrix LR:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Confussion Matrix DT:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [93]:
from sklearn.metrics import precision_score,recall_score,f1_score

print("Precision score:",precision_score(y_test,y_pred,average='micro'))
print("Recall:",recall_score(y_test,y_pred,average='macro'))
print("F1 Score:",f1_score(y_test,y_pred,average='weighted'))


Precision score: 1.0
Recall: 1.0
F1 Score: 1.0


In [94]:
print("Precision score:",precision_score(y_test,y_pred1,average='micro'))
print("Recall:",recall_score(y_test,y_pred1,average='macro'))
print("F1 Score:",f1_score(y_test,y_pred1,average='weighted'))

Precision score: 1.0
Recall: 1.0
F1 Score: 1.0
