In [7]:
import tensorflow_hub as hub
import tensorflow_text as text

In [8]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [ ]:
text_test = ["nice movie indeed","I love python programming"]

text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [12]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [13]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [14]:
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [15]:
bert_model = hub.KerasLayer(encoder_url)

In [17]:
bert_results = bert_model(text_preprocessed)

In [18]:
bert_results.keys()

dict_keys(['default', 'pooled_output', 'sequence_output', 'encoder_outputs'])

In [19]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.0729203 ,  0.08567806,  0.14476833, ..., -0.09677095,
          0.08722141,  0.07711083],
        [ 0.1783942 , -0.19006135,  0.50349474, ..., -0.05869776,
          0.32717073, -0.15578511],
        [ 0.18701458, -0.43388766, -0.48875168, ..., -0.1550283 ,
          0.00145148, -0.24470986],
        ...,
        [ 0.12083128,  0.12884232,  0.46453533, ...,  0.07375553,
          0.17441972,  0.1652206 ],
        [ 0.07967931, -0.01190672,  0.50225437, ...,  0.13777766,
          0.21002245,  0.00624563],
        [-0.07212669, -0.2830347 ,  0.5903337 , ...,  0.47551915,
          0.16668504, -0.08920358]],

       [[-0.07900602,  0.36335096, -0.21101578, ..., -0.17183776,
          0.1629977 ,  0.672427  ],
        [ 0.27883476,  0.43716255, -0.35764766, ..., -0.04463655,
          0.38315225,  0.58879846],
        [ 1.2037675 ,  1.0727019 ,  0.48408765, ...,  0.2492101 ,
          0.407309  ,  0.40481824],
        ...,

In [20]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917741 , -0.2141193 ,  0.49769473, ...,  0.24465191,
        -0.47334483,  0.81758696],
       [-0.9171231 , -0.4793519 , -0.78656995, ..., -0.6175178 ,
        -0.7102687 ,  0.921843  ]], dtype=float32)>

In [21]:
len(bert_results['encoder_outputs'])

12

In [22]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901434,  0.00644744, -0.03614972, ...,  0.04999615,
           0.06149198, -0.02657542],
         [ 1.1753384 ,  1.2140785 ,  1.1569979 , ...,  0.11634347,
          -0.3585535 , -0.4049017 ],
         [ 0.0385906 ,  0.53869975, -0.21089801, ...,  0.21858175,
           0.72601646, -1.1158605 ],
         ...,
         [-0.07587029, -0.25421906,  0.7075512 , ...,  0.5054199 ,
          -0.18878672,  0.15028355],
         [-0.16066611, -0.2808968 ,  0.57597053, ...,  0.52758545,
          -0.11141385,  0.02887557],
         [-0.04428164, -0.2027957 ,  0.5909355 , ...,  0.8133834 ,
          -0.39075816, -0.02601739]],
 
        [[ 0.18903589,  0.02752547, -0.06513736, ..., -0.00620204,
           0.15053889,  0.03165445],
         [ 0.5916151 ,  0.7589141 , -0.0724066 , ...,  0.61903965,
           0.8292889 ,  0.16161957],
         [ 1.446083  ,  0.44602644,  0.4099025 , ...,  0.48255908,
           0.62691146,  0.13